export const MODERATOR_ROUTE = '/moderator'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/shop'
export const BASKET_ROUTE = '/basket'
export const FOOD_ROUTE = '/food'